#!/bin/bash
set -e

echo "Setting up Python Virtual Environment..."
cd /opt/trending-api
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

echo "Configuring Systemd Service..."
systemctl daemon-reload
systemctl enable trending-api.service
systemctl start trending-api.service

echo "Configuring UFW Firewall to open port 8000..."
ufw allow 8000/tcp

exit 0

