bootstrap.servers=kafka1:19092,kafka2:19093,kafka3:19094

group.id=logistics-consumer-group

auto.offset.reset=earliest

enable.auto.commit=true

key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

max.poll.records=500