bootstrap.servers=kafka1:19092,kafka2:19093,kafka3:19094

acks=all

compression.type=none

key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer

retries=3

linger.ms=5

batch.size=16384